apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibanadepl
  namespace: logging
  labels:
    component: kibana
spec:
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: kibana
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
#        resources:
#          limits:
#            memory: 1Gi
#        volumeMounts:
#        - name: storage
#          mountPath: /var/lib/elasticsearch
#        - name: config-volume
#          mountPath: /etc/elasticsearch
#      volumes:
#          - name: config-volume
#            configMap:
#              name: elastic-config
#          - emptyDir:
#              medium: ""
#            name: "storage"
